export const menuData = [
    {
        tit:'my组件库测试',
        details:[{
            tit:'综合测试',
            url:'/component/menu',
            details:[{
                tit:'第三级'
            }]
        }]
    },
    {
        tit:'标题2',
        url:'https://www.baidu.com'
    },
    {
        tit:'标题3',
        url:'https://www.baidu.com'
    },
    {
        tit:'标题4',
        url:'https://www.baidu.com'
    }
];
